/*
 * This file is generated by jOOQ.
 */
package com.codegen.liquibase;


import com.codegen.liquibase.tables.Bar;
import com.codegen.liquibase.tables.Foo;
import com.codegen.liquibase.tables.records.BarRecord;
import com.codegen.liquibase.tables.records.FooRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BarRecord> PK_BAR = Internal.createUniqueKey(Bar.BAR, DSL.name("PK_BAR"), new TableField[] { Bar.BAR.ID }, true);
    public static final UniqueKey<FooRecord> PK_FOO = Internal.createUniqueKey(Foo.FOO, DSL.name("PK_FOO"), new TableField[] { Foo.FOO.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BarRecord, FooRecord> FK_FOO_BAR = Internal.createForeignKey(Bar.BAR, DSL.name("FK_FOO_BAR"), new TableField[] { Bar.BAR.FOO_ID }, Keys.PK_FOO, new TableField[] { Foo.FOO.ID }, true);
}
