/*
 * This file is generated by jOOQ.
 */
package com.codegen.liquibase;


import com.codegen.liquibase.tables.Bar;
import com.codegen.liquibase.tables.Foo;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>BAR</code>.
     */
    public static final Bar BAR = Bar.BAR;

    /**
     * The table <code>FOO</code>.
     */
    public static final Foo FOO = Foo.FOO;
}
