/*
 * This file is generated by jOOQ.
 */
package com.codegen.testcontainer.mysql;


import com.codegen.testcontainer.mysql.tables.Bar;
import com.codegen.testcontainer.mysql.tables.Databasechangeloglock;
import com.codegen.testcontainer.mysql.tables.Foo;
import com.codegen.testcontainer.mysql.tables.records.BarRecord;
import com.codegen.testcontainer.mysql.tables.records.DatabasechangeloglockRecord;
import com.codegen.testcontainer.mysql.tables.records.FooRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BarRecord> KEY_BAR_PRIMARY = Internal.createUniqueKey(Bar.BAR, DSL.name("KEY_bar_PRIMARY"), new TableField[] { Bar.BAR.ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("KEY_DATABASECHANGELOGLOCK_PRIMARY"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<FooRecord> KEY_FOO_PRIMARY = Internal.createUniqueKey(Foo.FOO, DSL.name("KEY_foo_PRIMARY"), new TableField[] { Foo.FOO.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BarRecord, FooRecord> FK_FOO_BAR = Internal.createForeignKey(Bar.BAR, DSL.name("fk_foo_bar"), new TableField[] { Bar.BAR.FOO_ID }, Keys.KEY_FOO_PRIMARY, new TableField[] { Foo.FOO.ID }, true);
}
