/*
 * This file is generated by jOOQ.
 */
package com.codegen.testcontainer.mysql.tables.records;


import com.codegen.testcontainer.mysql.tables.Bar;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BarRecord extends UpdatableRecordImpl<BarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bar.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bar.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bar.bar_name</code>.
     */
    public void setBarName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bar.bar_name</code>.
     */
    public String getBarName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bar.foo_id</code>.
     */
    public void setFooId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bar.foo_id</code>.
     */
    public Integer getFooId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BarRecord
     */
    public BarRecord() {
        super(Bar.BAR);
    }

    /**
     * Create a detached, initialised BarRecord
     */
    public BarRecord(Integer id, String barName, Integer fooId) {
        super(Bar.BAR);

        setId(id);
        setBarName(barName);
        setFooId(fooId);
        resetChangedOnNotNull();
    }
}
