/*
 * This file is generated by jOOQ.
 */
package com.codegen.testcontainer.postgres;


import com.codegen.testcontainer.postgres.tables.Bar;
import com.codegen.testcontainer.postgres.tables.Databasechangelog;
import com.codegen.testcontainer.postgres.tables.Databasechangeloglock;
import com.codegen.testcontainer.postgres.tables.Foo;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>bar</code>.
     */
    public static final Bar BAR = Bar.BAR;

    /**
     * The table <code>databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>foo</code>.
     */
    public static final Foo FOO = Foo.FOO;
}
